### ISSUE TITLE
Simulated head control doesn't match reality

### ISSUE THREAD

**Issue by dljsjr** [ihmcrobotics/ihmc-open-robotics-software#6]
Originally reported by: **Maurice Fallon (Bitbucket: [mauricefallon](http://bitbucket.org/mauricefallon), GitHub: [mauricefallon](http://github.com/mauricefallon))**

----------------------------------------

We would like to implement automated head tracking ('Look At Target'). Currently the head orientation control on the robot (QP) and the simulator (joint position) is implemented differently. 

It's not clear if the same HeadOrientationPacket commands in simulation and reality achieve the same look direction. Do they?

This issue was mentioned here:
https://bitbucket.org/ihmcrobotics/ihmc_ros/issues/53/headorientationpacketmessage-documentation

BTW: @btshrewsbury 's comment on that ticket mentions that the problem is the redundant joint (UPPER_NECK_PITCH), but you could just remove it from the QP and not support looking up?

----------------------------------------
- Bitbucket: https://bitbucket.org/ihmcrobotics/ihmc-open-robotics-software/issue/2

**Comment by SylvainBertrand** [comment]
With the new controller, you'll have access to an extended API for controlling the head:
- HeadTrajectoryMessage: Message to control the head in task-space. If you're using HeadOrientationPacket, this will be the one you'll want to switch to. In addition to being able to send a single endpoint (as the HeadOrientationPacket), this message offers the option to send a series of trajectory points to go through.
- NeckTrajectoryMessage: Message to control the head in joint-space.
- NeckDesiredAccelerationsMessage: Message to directly provide the neck joint desired accelerations.

I've been working on the issue related to the redundancy of the neck joints. When controlled in task-space, there is still some minor issues due to the redundancy but the controller is stable and converges to the desired orientation which is much better than before. I hope to get that controller to be working better over time. Since the two other modes are in joint-space, there will no issue with NeckTrajectoryMessages nor NeckDesiredAccelerationsMessages.
